# Generated by Django 5.0.6 on 2024-06-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White')], max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'Xl'), ('XXL', 'Xxl'), ('XXXL', 'Xxxl'), ('Free', 'Free')], max_length=4, unique=True),
        ),
    ]
