# Generated by Django 5.0.6 on 2024-06-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_color_name_alter_size_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wc_consumer_key', models.CharField(blank=True, default='', max_length=64)),
                ('wc_consumer_secret', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
