# Generated by Django 5.0.6 on 2024-06-13 09:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="wc_order_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="wc_order_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="logo_variation",
            field=models.CharField(
                choices=[
                    ("Default", "Default"),
                    ("Rzzy", "Rzzy"),
                    ("Attack On Titan", "Aot"),
                    ("Onepiece 3D2Y", "Op3D2Y"),
                    ("Berserk", "Berserk"),
                ],
                default="Default",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="wc_item_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="wc_product_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="settings",
            name="ncm_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="settings",
            name="wc_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processed", "Processed"),
                    ("On Hold", "Onhold"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                    ("Disputed", "Disputed"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                    ("Draft", "Draft"),
                ],
                default="Pending",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="wc_consumer_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="settings",
            name="wc_consumer_secret",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
